# Generated by Django 4.1.1 on 2022-10-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('Volta', 'Volta')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_routes', models.IntegerField()),
                ('min_number_of_passengers', models.IntegerField()),
                ('max_number_of_passengers', models.IntegerField()),
                ('max_number_of_bus_stops', models.IntegerField()),
                ('max_traveling_time', models.IntegerField()),
                ('max_distance_to_house', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('bus_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buson_app.busstop')),
            ],
        ),
        migrations.AddField(
            model_name='busstop',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buson_app.route'),
        ),
    ]
