# Generated by Django 4.1.1 on 2022-10-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buson_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(default='AAAA-MM-DD', verbose_name='Data de Nascimento'),
        ),
    ]
