# Generated by Django 4.1.2 on 2022-10-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buson_app', '0002_alter_employee_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='neighborhood',
            new_name='district',
        ),
    ]
