# Generated by Django 4.1.2 on 2022-10-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buson_app', '0003_rename_neighborhood_address_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bus_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='buson_app.busstop'),
        ),
    ]
