# Generated by Django 4.1.2 on 2022-10-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buson_app', '0004_employee_bus_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, default='AAAA-MM-DD', null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.CharField(blank=True, default='XXX.XXX.XXX-XX', max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, default='(XX) XXXX-XXXX', max_length=16, null=True, verbose_name='Telefone'),
        ),
    ]
